substitutions:
  _SCANNER_CLI_VERSION: '4.6.0.2311'
steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "build"
      - "--build-arg"
      - "SONARQUBE_SCANNER_CLI_VERSION=$_SCANNER_CLI_VERSION"
      - "-t"
      - "gcr.io/$PROJECT_ID/sonar-scanner:latest"
      - "-t"
      - "gcr.io/$PROJECT_ID/sonar-scanner:$_SCANNER_CLI_VERSION"
      - "."

images:
  - "gcr.io/$PROJECT_ID/sonar-scanner:latest"
  - "gcr.io/$PROJECT_ID/sonar-scanner:$_SCANNER_CLI_VERSION"

tags: ["sonar-scanner-cloud-builder"]
